### PR TITLE
Create assembly definitions

### PR DESCRIPTION
**Pull request by AlexWolski**
Created Assembly Definition files to organize code and allow for Unit Tests.

- The scripts in `Assets/ThirdParty` were moved to `Assets/Scripts`
- New Assembly definitions were created for the Discord plugin, Photon plugin, main Scripts folder, and a new Tests folder

Scripts Assembly Definition
Discord Assembly Definition
Photon Assembly Definition
Tests Assembly Definition
Text Example

### CODE REVIEW

**Comment by AutumnThyme** [comment]
Does this add any overhead to the project?
I remember a ton of these unity asset/project helpers absolutely killing loading times for the original project.

**Comment by AutumnThyme** [comment]
Also gl getting devs to write tests, but this is good if it doesn't add overhead/loading whenever I do anything in unity

**Comment by AlexWolski** [comment]
@AutumnThyme I don't believe it adds any overhead. All of these scripts were being compiled into a monolith `Assembly-CSharp.dll` file. By making the assemblies modular, the compilation time should speed up. But the only optimization in this PR are to the 7 Discord scripts, so you won't be seeing much difference. Maybe we can organize the scripts more and get a real speed up.
[Assembly Definitions](https://docs.unity3d.com/2018.4/Documentation/Manual/ScriptCompilationAssemblyDefinitionFiles.html)

I have a unit test file I want to write so that's one dev :P

**Comment by mwnDK1402** [comment]
> Also gl getting devs to write tests, but this is good if it doesn't add overhead/loading whenever I do anything in unity

OH MY GOD, CAN I FINALLY WRITE TESTS?! HOLY SHIT!

**Comment by mwnDK1402** [comment]
I think there's reason to separate third-party code from ours. Why was ThirdParty/ moved into Scripts/?

**Comment by AlexWolski** [comment]
> I think there's reason to separate third-party code from ours. Why was ThirdParty/ moved into Scripts/?

Because they are interdependent and would cause a circular reference. They need to be decoupled first. I forget exactly which scripts in the third party folder referenced the main scripts.

**Comment by mwnDK1402** [comment]
> > I think there's reason to separate third-party code from ours. Why was ThirdParty/ moved into Scripts/?
> 
> Because they are interdependent and would cause a circular reference. They need to be decoupled first. I forget exactly which scripts in the third party folder referenced the main scripts.

If they were truly third-party, they couldn't possibly reference our code. I'll give it a look. 👍

**Comment by AlexWolski** [comment]
@mwnDK1402 Oh, I think you're right. They reference each other, not the main scripts folder. Let me revert that change.

**Comment by AlexWolski** [comment]
@mwnDK1402 `MeleeWeaponTrail.cs` has one reference to `Scripts/ApplicationManagers/SceneLoader.cs` to disable the behavior when there is no camera in the scene. This can be refactored so that the SceneLoader calls and enables/disables MeleeWeaponTrail instead.

**Comment by AlexWolski** [comment]
@mwnDK1402 Implemented your suggestion. Everything looks to build and work including weapon trails.
- Added new assembly definition files for MeleeWeaponTrail and Standard Assets
- Replaced the camera null-check in MeleeWeaponTrail with a public boolean property

**Comment by rc174945** [comment]
I would just move meleeweapontrail into main scripts. Null checking this way is unpredictable and hard for me to review. We can make an exception for this package since it is just a single script.

Also, do you know how the multiple assembly building impacts il2cpp building? Will we still have a single game assembly?

**Comment by AlexWolski** [comment]
@rc174945 I reverted the changes made to `MeleeWeaponTrail.cs` and moved it into the scripts folder.
I'm seeing a lot of dll files in the build folder. I assume these will be separate game assemblies in the final build?
Assembly files

Btw since I ran git clean, I've been unable to build this branch or the main branch due to shader compilation errors. I think I need to reinstall unity (I hate you unity.) I'd appreciate it if someone could try doing a fresh build on this branch to make sure everything is working.

**Review by rc174945 — APPROVED** [review]

**Comment by AlexWolski** [comment]
@rc174945 I pulled the latest commit on main and did a test build. There is one build issue caused by an unused import for IMGUI. Once the import is removed, everything seems to work perfectly. I'll create a PR to fix this.
Unused import
Supply Special unused import

**Comment by AlexWolski** [comment]
@rc174945 Actually, after another git clean, the shader errors are back. The built exe can't be launched. Maybe the merge should be rolled back.

**Pull request merged**
